name: Upload CSV

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download CSV from Google Drive
        run: |
          file_id="1Ol9nI-PLZXqNLCrTGe0NI8FLA7YjyXJm"
          curl -c /tmp/cookie -s -L "https://drive.google.com/uc?export=download&id=${file_id}" > /dev/null
          curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=$(awk '/download/ {print $NF}' /tmp/cookie)&id=${file_id}" -o symbols.csv

      - name: Print CSV content
        run: cat symbols.csv

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add symbols.csv
          git commit -m "Update CSV file"
          git push
